#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 10 14:17:59 2020

@author: Splurket
"""
import imaplib
import email
from email.header import decode_header
import webbrowser
import os
import sys
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import requests
username = "YOUR EMAIL"
password= "EMAIL PASSWORD"
imap_url = "imap.gmail.com"


def clean(text):
    # clean text for creating a folder
    return "".join(c if c.isalnum() else "_" for c in text)

# create an IMAP4 class with SSL 
imap = imaplib.IMAP4_SSL("imap.gmail.com")
# authenticate
imap.login(username, password)

status, messages = imap.select("Inbox")
# number of top emails to fetch
N = 1
# total number of emails
messages = int(messages[0])
for i in range(messages, messages-N, -1):
    # fetch the email message by ID
    res, msg = imap.fetch(str(i), "(RFC822)")
    for response in msg:
        if isinstance(response, tuple):
            # parse a bytes email into a message object
            msg = email.message_from_bytes(response[1])
            # decode the email subject
            subject, encoding = decode_header(msg["Subject"])[0]
            if isinstance(subject, bytes):
                # if it's a bytes, decode to str
                subject = subject.decode(encoding)
            # decode email sender
            From, encoding = decode_header(msg.get("From"))[0]
            if isinstance(From, bytes):
                From = From.decode(encoding)
            #print("Subject:", subject)
           # print("From:", From)
            # if the email message is multipart
            if msg.is_multipart():
                # iterate over email parts
                for part in msg.walk():
                    # extract content type of email
                    content_type = part.get_content_type()
                    content_disposition = str(part.get("Content-Disposition"))
                    try:
                        # get the email body
                        body = part.get_payload(decode=True).decode()
                    except:
                        pass
                    if content_type == "text/plain" and "attachment" not in content_disposition:
                        # use creds to create a client to interact with the Google Drive API
                        scope = ['https://spreadsheets.google.com/feeds',
                                 'https://www.googleapis.com/auth/drive']
                        creds = ServiceAccountCredentials.from_json_keyfile_name('PATH TO CLIENT_SECRET.JSON GENERATED BY GOOGLE', scope)
                        client = gspread.authorize(creds)

                        key="TRELLO API KEY"
                        token="TRELLO API TOKEN"
                        # Find a workbook by name and open the first sheet
                        # Make sure you use the right name here.
                        sheet = client.open("YOUR SHEET NAME").sheet1
                        
                        name=sheet.cell(subject,2).value
                        email=sheet.cell(subject,3).value
                        Sample=sheet.cell(subject,4).value
                        if "Yes" in Sample:
                            #print('You think we'll win!')
                            idList='TRELLO LIST ID'
                            
                            #define What cells To grab from sheet and assign variables
                            Wanimal=sheet.cell(subject,5)
                            Rtype=sheet.cell(subject, 6)
                            url = ('https://api.trello.com/1/cards?key='+ key +'&token='+ token+'&idList='+ idList+'&name='+name)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            r=response.text
                            
                            #print(r)
                            chunks=r.split(',')
                            #print(chunks)
                            card_id= chunks[:1]
                            hi=str(card_id)
                            idlist=hi.split('"')
                            #print(idlist)
                            shit, more_shit,less_shit,cardid= idlist[:4]
                            #print(cardid)
                            url ='https://api.trello.com/1/checklists?key='+key+'&token='+token+'&idCard=' +cardid+ "&name=More Info About Form Response"  
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            hi1=response.text
                            #print(hi1)
                            #print(r)
                            chunks=hi1.split(',')
                            #print(chunks)
                            checkid= chunks[:1]
                            hi=str(checkid)
                            idlist=hi.split('"')
                            #print(idlist)
                            shit, more_shit,less_shit,checklistid= idlist[:4]
                            #print(checklistid)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name=Name:'+str(name)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name=Email:'+str(email)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name=Think we\'ll win?:'+str(Sample)
                            payload = {}
                            headers= {} 
                            response = requests.request("POST", url, headers=headers, data = payload)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name=Favorite color:'+str(Rtype)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name=Favorite Animal:'+str(Wanimal)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                        if "No" in Sample:
                            #print('You chose No!')
                            idList='TRELLO LIST ID'
                            Wanimal=sheet.cell(subject,8)
                            Rtype=sheet.cell(subject, 7)
                            url = ('https://api.trello.com/1/cards?key='+ key +'&token='+ token+'&idList='+ idList+'&name='+name)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            r=response.text
                            
                            #print(r)
                            chunks=r.split(',')
                            #print(chunks)
                            card_id= chunks[:1]
                            hi=str(card_id)
                            idlist=hi.split('"')
                            #print(idlist)
                            shit, more_shit,less_shit,cardid= idlist[:4]
                            #print(cardid)
                            url ='https://api.trello.com/1/checklists?key='+key+'&token='+token+'&idCard=' +cardid+ "&name=More Info About Form Response"  
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            hi1=response.text
                            #print(hi1)
                            #print(r)
                            chunks=hi1.split(',')
                            #print(chunks)
                            checkid= chunks[:1]
                            hi=str(checkid)
                            idlist=hi.split('"')
                            #print(idlist)
                            shit, more_shit,less_shit,checklistid= idlist[:4]
                            #print(checklistid)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name=Name:'+str(name)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name= Email:'+str(email)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name=Think we\'ll win?:'+str(Sample)
                            payload = {}
                            headers= {} 
                            response = requests.request("POST", url, headers=headers, data = payload)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name=Favorite color:'+str(Rtype)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
                            
                            url= 'https://api.trello.com/1/checklists/'+checklistid+'/checkItems?key='+key+'&token='+token+'&name=Favorite Animal:'+str(Wanimal)
                            payload = {}
                            headers= {}
                            response = requests.request("POST", url, headers=headers, data = payload)
